# Code generated by moonworm : https://github.com/bugout-dev/moonworm
# Moonworm version : 0.6.2

import argparse
import json
import os
from pathlib import Path
from typing import Any, Dict, List, Optional, Union

from brownie import Contract, network, project
from brownie.network.contract import ContractContainer
from eth_typing.evm import ChecksumAddress


PROJECT_DIRECTORY = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
BUILD_DIRECTORY = os.path.join(PROJECT_DIRECTORY, "build", "contracts")


def boolean_argument_type(raw_value: str) -> bool:
    TRUE_VALUES = ["1", "t", "y", "true", "yes"]
    FALSE_VALUES = ["0", "f", "n", "false", "no"]

    if raw_value.lower() in TRUE_VALUES:
        return True
    elif raw_value.lower() in FALSE_VALUES:
        return False

    raise ValueError(
        f"Invalid boolean argument: {raw_value}. Value must be one of: {','.join(TRUE_VALUES + FALSE_VALUES)}"
    )


def bytes_argument_type(raw_value: str) -> str:
    return raw_value


def get_abi_json(abi_name: str) -> List[Dict[str, Any]]:
    abi_full_path = os.path.join(BUILD_DIRECTORY, f"{abi_name}.json")
    if not os.path.isfile(abi_full_path):
        raise IOError(
            f"File does not exist: {abi_full_path}. Maybe you have to compile the smart contracts?"
        )

    with open(abi_full_path, "r") as ifp:
        build = json.load(ifp)

    abi_json = build.get("abi")
    if abi_json is None:
        raise ValueError(f"Could not find ABI definition in: {abi_full_path}")

    return abi_json


def contract_from_build(abi_name: str) -> ContractContainer:
    # This is workaround because brownie currently doesn't support loading the same project multiple
    # times. This causes problems when using multiple contracts from the same project in the same
    # python project.
    PROJECT = project.main.Project("moonworm", Path(PROJECT_DIRECTORY))

    abi_full_path = os.path.join(BUILD_DIRECTORY, f"{abi_name}.json")
    if not os.path.isfile(abi_full_path):
        raise IOError(
            f"File does not exist: {abi_full_path}. Maybe you have to compile the smart contracts?"
        )

    with open(abi_full_path, "r") as ifp:
        build = json.load(ifp)

    return ContractContainer(PROJECT, build)


class BasicEthereal:
    def __init__(self, contract_address: Optional[ChecksumAddress]):
        self.contract_name = "BasicEthereal"
        self.address = contract_address
        self.contract = None
        self.abi = get_abi_json("BasicEthereal")
        if self.address is not None:
            self.contract: Optional[Contract] = Contract.from_abi(
                self.contract_name, self.address, self.abi
            )

    def deploy(self, name_arg: str, symbol_arg: str, transaction_config):
        contract_class = contract_from_build(self.contract_name)
        deployed_contract = contract_class.deploy(
            name_arg, symbol_arg, transaction_config
        )
        self.address = deployed_contract.address
        self.contract = deployed_contract
        return deployed_contract.tx

    def assert_contract_is_instantiated(self) -> None:
        if self.contract is None:
            raise Exception("contract has not been instantiated")

    def verify_contract(self):
        self.assert_contract_is_instantiated()
        contract_class = contract_from_build(self.contract_name)
        contract_class.publish_source(self.contract)

    def current_ethereal_token_id(
        self, arg1: int, arg2: int, block_number: Optional[Union[str, int]] = "latest"
    ) -> Any:
        self.assert_contract_is_instantiated()
        return self.contract.CurrentEtherealTokenID.call(
            arg1, arg2, block_identifier=block_number
        )

    def live_until(
        self, arg1: int, block_number: Optional[Union[str, int]] = "latest"
    ) -> Any:
        self.assert_contract_is_instantiated()
        return self.contract.LiveUntil.call(arg1, block_identifier=block_number)

    def metadata_uri(
        self, arg1: int, block_number: Optional[Union[str, int]] = "latest"
    ) -> Any:
        self.assert_contract_is_instantiated()
        return self.contract.MetadataURI.call(arg1, block_identifier=block_number)

    def source(
        self, arg1: int, block_number: Optional[Union[str, int]] = "latest"
    ) -> Any:
        self.assert_contract_is_instantiated()
        return self.contract.Source.call(arg1, block_identifier=block_number)

    def source_token_id(
        self, arg1: int, block_number: Optional[Union[str, int]] = "latest"
    ) -> Any:
        self.assert_contract_is_instantiated()
        return self.contract.SourceTokenID.call(arg1, block_identifier=block_number)

    def approve(self, to: ChecksumAddress, token_id: int, transaction_config) -> Any:
        self.assert_contract_is_instantiated()
        return self.contract.approve(to, token_id, transaction_config)

    def balance_of(
        self, owner: ChecksumAddress, block_number: Optional[Union[str, int]] = "latest"
    ) -> Any:
        self.assert_contract_is_instantiated()
        return self.contract.balanceOf.call(owner, block_identifier=block_number)

    def create(
        self,
        recipient: ChecksumAddress,
        token_id: int,
        source_id: int,
        source_token_id: int,
        live_until: int,
        metadata_uri: str,
        signer: ChecksumAddress,
        signature: bytes,
        transaction_config,
    ) -> Any:
        self.assert_contract_is_instantiated()
        return self.contract.create(
            recipient,
            token_id,
            source_id,
            source_token_id,
            live_until,
            metadata_uri,
            signer,
            signature,
            transaction_config,
        )

    def create_message_hash(
        self,
        recipient: ChecksumAddress,
        token_id: int,
        source_id: int,
        source_token_id: int,
        live_until: int,
        metadata_uri: str,
        block_number: Optional[Union[str, int]] = "latest",
    ) -> Any:
        self.assert_contract_is_instantiated()
        return self.contract.createMessageHash.call(
            recipient,
            token_id,
            source_id,
            source_token_id,
            live_until,
            metadata_uri,
            block_identifier=block_number,
        )

    def destroy(self, token_id: int, transaction_config) -> Any:
        self.assert_contract_is_instantiated()
        return self.contract.destroy(token_id, transaction_config)

    def get_approved(
        self, token_id: int, block_number: Optional[Union[str, int]] = "latest"
    ) -> Any:
        self.assert_contract_is_instantiated()
        return self.contract.getApproved.call(token_id, block_identifier=block_number)

    def is_approved_for_all(
        self,
        owner: ChecksumAddress,
        operator: ChecksumAddress,
        block_number: Optional[Union[str, int]] = "latest",
    ) -> Any:
        self.assert_contract_is_instantiated()
        return self.contract.isApprovedForAll.call(
            owner, operator, block_identifier=block_number
        )

    def is_signer_valid_for_source(
        self,
        signer: ChecksumAddress,
        source_id: int,
        block_number: Optional[Union[str, int]] = "latest",
    ) -> Any:
        self.assert_contract_is_instantiated()
        return self.contract.isSignerValidForSource.call(
            signer, source_id, block_identifier=block_number
        )

    def name(self, block_number: Optional[Union[str, int]] = "latest") -> Any:
        self.assert_contract_is_instantiated()
        return self.contract.name.call(block_identifier=block_number)

    def owner(self, block_number: Optional[Union[str, int]] = "latest") -> Any:
        self.assert_contract_is_instantiated()
        return self.contract.owner.call(block_identifier=block_number)

    def owner_of(
        self, token_id: int, block_number: Optional[Union[str, int]] = "latest"
    ) -> Any:
        self.assert_contract_is_instantiated()
        return self.contract.ownerOf.call(token_id, block_identifier=block_number)

    def renounce_ownership(self, transaction_config) -> Any:
        self.assert_contract_is_instantiated()
        return self.contract.renounceOwnership(transaction_config)

    def safe_transfer_from_0x42842e0e(
        self,
        from_: ChecksumAddress,
        to: ChecksumAddress,
        token_id: int,
        transaction_config,
    ) -> Any:
        self.assert_contract_is_instantiated()
        return self.contract.safeTransferFrom(from_, to, token_id, transaction_config)

    def safe_transfer_from_0xb88d4fde(
        self,
        from_: ChecksumAddress,
        to: ChecksumAddress,
        token_id: int,
        data: bytes,
        transaction_config,
    ) -> Any:
        self.assert_contract_is_instantiated()
        return self.contract.safeTransferFrom(
            from_, to, token_id, data, transaction_config
        )

    def set_approval_for_all(
        self, operator: ChecksumAddress, approved: bool, transaction_config
    ) -> Any:
        self.assert_contract_is_instantiated()
        return self.contract.setApprovalForAll(operator, approved, transaction_config)

    def supports_interface(
        self, interface_id: bytes, block_number: Optional[Union[str, int]] = "latest"
    ) -> Any:
        self.assert_contract_is_instantiated()
        return self.contract.supportsInterface.call(
            interface_id, block_identifier=block_number
        )

    def symbol(self, block_number: Optional[Union[str, int]] = "latest") -> Any:
        self.assert_contract_is_instantiated()
        return self.contract.symbol.call(block_identifier=block_number)

    def token_uri(
        self, token_id: int, block_number: Optional[Union[str, int]] = "latest"
    ) -> Any:
        self.assert_contract_is_instantiated()
        return self.contract.tokenURI.call(token_id, block_identifier=block_number)

    def transfer_from(
        self,
        from_: ChecksumAddress,
        to: ChecksumAddress,
        token_id: int,
        transaction_config,
    ) -> Any:
        self.assert_contract_is_instantiated()
        return self.contract.transferFrom(from_, to, token_id, transaction_config)

    def transfer_ownership(self, new_owner: ChecksumAddress, transaction_config) -> Any:
        self.assert_contract_is_instantiated()
        return self.contract.transferOwnership(new_owner, transaction_config)


def get_transaction_config(args: argparse.Namespace) -> Dict[str, Any]:
    signer = network.accounts.load(args.sender, args.password)
    transaction_config: Dict[str, Any] = {"from": signer}
    if args.gas_price is not None:
        transaction_config["gas_price"] = args.gas_price
    if args.max_fee_per_gas is not None:
        transaction_config["max_fee"] = args.max_fee_per_gas
    if args.max_priority_fee_per_gas is not None:
        transaction_config["priority_fee"] = args.max_priority_fee_per_gas
    if args.confirmations is not None:
        transaction_config["required_confs"] = args.confirmations
    if args.nonce is not None:
        transaction_config["nonce"] = args.nonce
    return transaction_config


def add_default_arguments(parser: argparse.ArgumentParser, transact: bool) -> None:
    parser.add_argument(
        "--network", required=True, help="Name of brownie network to connect to"
    )
    parser.add_argument(
        "--address", required=False, help="Address of deployed contract to connect to"
    )
    if not transact:
        parser.add_argument(
            "--block-number",
            required=False,
            type=int,
            help="Call at the given block number, defaults to latest",
        )
        return
    parser.add_argument(
        "--sender", required=True, help="Path to keystore file for transaction sender"
    )
    parser.add_argument(
        "--password",
        required=False,
        help="Password to keystore file (if you do not provide it, you will be prompted for it)",
    )
    parser.add_argument(
        "--gas-price", default=None, help="Gas price at which to submit transaction"
    )
    parser.add_argument(
        "--max-fee-per-gas",
        default=None,
        help="Max fee per gas for EIP1559 transactions",
    )
    parser.add_argument(
        "--max-priority-fee-per-gas",
        default=None,
        help="Max priority fee per gas for EIP1559 transactions",
    )
    parser.add_argument(
        "--confirmations",
        type=int,
        default=None,
        help="Number of confirmations to await before considering a transaction completed",
    )
    parser.add_argument(
        "--nonce", type=int, default=None, help="Nonce for the transaction (optional)"
    )
    parser.add_argument(
        "--value", default=None, help="Value of the transaction in wei(optional)"
    )
    parser.add_argument("--verbose", action="store_true", help="Print verbose output")


def handle_deploy(args: argparse.Namespace) -> None:
    network.connect(args.network)
    transaction_config = get_transaction_config(args)
    contract = BasicEthereal(None)
    result = contract.deploy(
        name_arg=args.name_arg,
        symbol_arg=args.symbol_arg,
        transaction_config=transaction_config,
    )
    print(result)
    if args.verbose:
        print(result.info())


def handle_verify_contract(args: argparse.Namespace) -> None:
    network.connect(args.network)
    contract = BasicEthereal(args.address)
    result = contract.verify_contract()
    print(result)


def handle_current_ethereal_token_id(args: argparse.Namespace) -> None:
    network.connect(args.network)
    contract = BasicEthereal(args.address)
    result = contract.current_ethereal_token_id(
        arg1=args.arg1, arg2=args.arg2, block_number=args.block_number
    )
    print(result)


def handle_live_until(args: argparse.Namespace) -> None:
    network.connect(args.network)
    contract = BasicEthereal(args.address)
    result = contract.live_until(arg1=args.arg1, block_number=args.block_number)
    print(result)


def handle_metadata_uri(args: argparse.Namespace) -> None:
    network.connect(args.network)
    contract = BasicEthereal(args.address)
    result = contract.metadata_uri(arg1=args.arg1, block_number=args.block_number)
    print(result)


def handle_source(args: argparse.Namespace) -> None:
    network.connect(args.network)
    contract = BasicEthereal(args.address)
    result = contract.source(arg1=args.arg1, block_number=args.block_number)
    print(result)


def handle_source_token_id(args: argparse.Namespace) -> None:
    network.connect(args.network)
    contract = BasicEthereal(args.address)
    result = contract.source_token_id(arg1=args.arg1, block_number=args.block_number)
    print(result)


def handle_approve(args: argparse.Namespace) -> None:
    network.connect(args.network)
    contract = BasicEthereal(args.address)
    transaction_config = get_transaction_config(args)
    result = contract.approve(
        to=args.to, token_id=args.token_id, transaction_config=transaction_config
    )
    print(result)
    if args.verbose:
        print(result.info())


def handle_balance_of(args: argparse.Namespace) -> None:
    network.connect(args.network)
    contract = BasicEthereal(args.address)
    result = contract.balance_of(owner=args.owner, block_number=args.block_number)
    print(result)


def handle_create(args: argparse.Namespace) -> None:
    network.connect(args.network)
    contract = BasicEthereal(args.address)
    transaction_config = get_transaction_config(args)
    result = contract.create(
        recipient=args.recipient,
        token_id=args.token_id,
        source_id=args.source_id,
        source_token_id=args.source_token_id,
        live_until=args.live_until,
        metadata_uri=args.metadata_uri,
        signer=args.signer_arg,
        signature=args.signature,
        transaction_config=transaction_config,
    )
    print(result)
    if args.verbose:
        print(result.info())


def handle_create_message_hash(args: argparse.Namespace) -> None:
    network.connect(args.network)
    contract = BasicEthereal(args.address)
    result = contract.create_message_hash(
        recipient=args.recipient,
        token_id=args.token_id,
        source_id=args.source_id,
        source_token_id=args.source_token_id,
        live_until=args.live_until,
        metadata_uri=args.metadata_uri,
        block_number=args.block_number,
    )
    print(result)


def handle_destroy(args: argparse.Namespace) -> None:
    network.connect(args.network)
    contract = BasicEthereal(args.address)
    transaction_config = get_transaction_config(args)
    result = contract.destroy(
        token_id=args.token_id, transaction_config=transaction_config
    )
    print(result)
    if args.verbose:
        print(result.info())


def handle_get_approved(args: argparse.Namespace) -> None:
    network.connect(args.network)
    contract = BasicEthereal(args.address)
    result = contract.get_approved(
        token_id=args.token_id, block_number=args.block_number
    )
    print(result)


def handle_is_approved_for_all(args: argparse.Namespace) -> None:
    network.connect(args.network)
    contract = BasicEthereal(args.address)
    result = contract.is_approved_for_all(
        owner=args.owner, operator=args.operator, block_number=args.block_number
    )
    print(result)


def handle_is_signer_valid_for_source(args: argparse.Namespace) -> None:
    network.connect(args.network)
    contract = BasicEthereal(args.address)
    result = contract.is_signer_valid_for_source(
        signer=args.signer_arg, source_id=args.source_id, block_number=args.block_number
    )
    print(result)


def handle_name(args: argparse.Namespace) -> None:
    network.connect(args.network)
    contract = BasicEthereal(args.address)
    result = contract.name(block_number=args.block_number)
    print(result)


def handle_owner(args: argparse.Namespace) -> None:
    network.connect(args.network)
    contract = BasicEthereal(args.address)
    result = contract.owner(block_number=args.block_number)
    print(result)


def handle_owner_of(args: argparse.Namespace) -> None:
    network.connect(args.network)
    contract = BasicEthereal(args.address)
    result = contract.owner_of(token_id=args.token_id, block_number=args.block_number)
    print(result)


def handle_renounce_ownership(args: argparse.Namespace) -> None:
    network.connect(args.network)
    contract = BasicEthereal(args.address)
    transaction_config = get_transaction_config(args)
    result = contract.renounce_ownership(transaction_config=transaction_config)
    print(result)
    if args.verbose:
        print(result.info())


def handle_safe_transfer_from_0x42842e0e(args: argparse.Namespace) -> None:
    network.connect(args.network)
    contract = BasicEthereal(args.address)
    transaction_config = get_transaction_config(args)
    result = contract.safe_transfer_from_0x42842e0e(
        from_=args.from_arg,
        to=args.to,
        token_id=args.token_id,
        transaction_config=transaction_config,
    )
    print(result)
    if args.verbose:
        print(result.info())


def handle_safe_transfer_from_0xb88d4fde(args: argparse.Namespace) -> None:
    network.connect(args.network)
    contract = BasicEthereal(args.address)
    transaction_config = get_transaction_config(args)
    result = contract.safe_transfer_from_0xb88d4fde(
        from_=args.from_arg,
        to=args.to,
        token_id=args.token_id,
        data=args.data,
        transaction_config=transaction_config,
    )
    print(result)
    if args.verbose:
        print(result.info())


def handle_set_approval_for_all(args: argparse.Namespace) -> None:
    network.connect(args.network)
    contract = BasicEthereal(args.address)
    transaction_config = get_transaction_config(args)
    result = contract.set_approval_for_all(
        operator=args.operator,
        approved=args.approved,
        transaction_config=transaction_config,
    )
    print(result)
    if args.verbose:
        print(result.info())


def handle_supports_interface(args: argparse.Namespace) -> None:
    network.connect(args.network)
    contract = BasicEthereal(args.address)
    result = contract.supports_interface(
        interface_id=args.interface_id, block_number=args.block_number
    )
    print(result)


def handle_symbol(args: argparse.Namespace) -> None:
    network.connect(args.network)
    contract = BasicEthereal(args.address)
    result = contract.symbol(block_number=args.block_number)
    print(result)


def handle_token_uri(args: argparse.Namespace) -> None:
    network.connect(args.network)
    contract = BasicEthereal(args.address)
    result = contract.token_uri(token_id=args.token_id, block_number=args.block_number)
    print(result)


def handle_transfer_from(args: argparse.Namespace) -> None:
    network.connect(args.network)
    contract = BasicEthereal(args.address)
    transaction_config = get_transaction_config(args)
    result = contract.transfer_from(
        from_=args.from_arg,
        to=args.to,
        token_id=args.token_id,
        transaction_config=transaction_config,
    )
    print(result)
    if args.verbose:
        print(result.info())


def handle_transfer_ownership(args: argparse.Namespace) -> None:
    network.connect(args.network)
    contract = BasicEthereal(args.address)
    transaction_config = get_transaction_config(args)
    result = contract.transfer_ownership(
        new_owner=args.new_owner, transaction_config=transaction_config
    )
    print(result)
    if args.verbose:
        print(result.info())


def generate_cli() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="CLI for BasicEthereal")
    parser.set_defaults(func=lambda _: parser.print_help())
    subcommands = parser.add_subparsers()

    deploy_parser = subcommands.add_parser("deploy")
    add_default_arguments(deploy_parser, True)
    deploy_parser.add_argument(
        "--name-arg", required=True, help="Type: string", type=str
    )
    deploy_parser.add_argument(
        "--symbol-arg", required=True, help="Type: string", type=str
    )
    deploy_parser.set_defaults(func=handle_deploy)

    verify_contract_parser = subcommands.add_parser("verify-contract")
    add_default_arguments(verify_contract_parser, False)
    verify_contract_parser.set_defaults(func=handle_verify_contract)

    current_ethereal_token_id_parser = subcommands.add_parser(
        "current-ethereal-token-id"
    )
    add_default_arguments(current_ethereal_token_id_parser, False)
    current_ethereal_token_id_parser.add_argument(
        "--arg1", required=True, help="Type: uint256", type=int
    )
    current_ethereal_token_id_parser.add_argument(
        "--arg2", required=True, help="Type: uint256", type=int
    )
    current_ethereal_token_id_parser.set_defaults(func=handle_current_ethereal_token_id)

    live_until_parser = subcommands.add_parser("live-until")
    add_default_arguments(live_until_parser, False)
    live_until_parser.add_argument(
        "--arg1", required=True, help="Type: uint256", type=int
    )
    live_until_parser.set_defaults(func=handle_live_until)

    metadata_uri_parser = subcommands.add_parser("metadata-uri")
    add_default_arguments(metadata_uri_parser, False)
    metadata_uri_parser.add_argument(
        "--arg1", required=True, help="Type: uint256", type=int
    )
    metadata_uri_parser.set_defaults(func=handle_metadata_uri)

    source_parser = subcommands.add_parser("source")
    add_default_arguments(source_parser, False)
    source_parser.add_argument("--arg1", required=True, help="Type: uint256", type=int)
    source_parser.set_defaults(func=handle_source)

    source_token_id_parser = subcommands.add_parser("source-token-id")
    add_default_arguments(source_token_id_parser, False)
    source_token_id_parser.add_argument(
        "--arg1", required=True, help="Type: uint256", type=int
    )
    source_token_id_parser.set_defaults(func=handle_source_token_id)

    approve_parser = subcommands.add_parser("approve")
    add_default_arguments(approve_parser, True)
    approve_parser.add_argument("--to", required=True, help="Type: address")
    approve_parser.add_argument(
        "--token-id", required=True, help="Type: uint256", type=int
    )
    approve_parser.set_defaults(func=handle_approve)

    balance_of_parser = subcommands.add_parser("balance-of")
    add_default_arguments(balance_of_parser, False)
    balance_of_parser.add_argument("--owner", required=True, help="Type: address")
    balance_of_parser.set_defaults(func=handle_balance_of)

    create_parser = subcommands.add_parser("create")
    add_default_arguments(create_parser, True)
    create_parser.add_argument("--recipient", required=True, help="Type: address")
    create_parser.add_argument(
        "--token-id", required=True, help="Type: uint256", type=int
    )
    create_parser.add_argument(
        "--source-id", required=True, help="Type: uint256", type=int
    )
    create_parser.add_argument(
        "--source-token-id", required=True, help="Type: uint256", type=int
    )
    create_parser.add_argument(
        "--live-until", required=True, help="Type: uint256", type=int
    )
    create_parser.add_argument(
        "--metadata-uri", required=True, help="Type: string", type=str
    )
    create_parser.add_argument("--signer-arg", required=True, help="Type: address")
    create_parser.add_argument(
        "--signature", required=True, help="Type: bytes", type=bytes_argument_type
    )
    create_parser.set_defaults(func=handle_create)

    create_message_hash_parser = subcommands.add_parser("create-message-hash")
    add_default_arguments(create_message_hash_parser, False)
    create_message_hash_parser.add_argument(
        "--recipient", required=True, help="Type: address"
    )
    create_message_hash_parser.add_argument(
        "--token-id", required=True, help="Type: uint256", type=int
    )
    create_message_hash_parser.add_argument(
        "--source-id", required=True, help="Type: uint256", type=int
    )
    create_message_hash_parser.add_argument(
        "--source-token-id", required=True, help="Type: uint256", type=int
    )
    create_message_hash_parser.add_argument(
        "--live-until", required=True, help="Type: uint256", type=int
    )
    create_message_hash_parser.add_argument(
        "--metadata-uri", required=True, help="Type: string", type=str
    )
    create_message_hash_parser.set_defaults(func=handle_create_message_hash)

    destroy_parser = subcommands.add_parser("destroy")
    add_default_arguments(destroy_parser, True)
    destroy_parser.add_argument(
        "--token-id", required=True, help="Type: uint256", type=int
    )
    destroy_parser.set_defaults(func=handle_destroy)

    get_approved_parser = subcommands.add_parser("get-approved")
    add_default_arguments(get_approved_parser, False)
    get_approved_parser.add_argument(
        "--token-id", required=True, help="Type: uint256", type=int
    )
    get_approved_parser.set_defaults(func=handle_get_approved)

    is_approved_for_all_parser = subcommands.add_parser("is-approved-for-all")
    add_default_arguments(is_approved_for_all_parser, False)
    is_approved_for_all_parser.add_argument(
        "--owner", required=True, help="Type: address"
    )
    is_approved_for_all_parser.add_argument(
        "--operator", required=True, help="Type: address"
    )
    is_approved_for_all_parser.set_defaults(func=handle_is_approved_for_all)

    is_signer_valid_for_source_parser = subcommands.add_parser(
        "is-signer-valid-for-source"
    )
    add_default_arguments(is_signer_valid_for_source_parser, False)
    is_signer_valid_for_source_parser.add_argument(
        "--signer-arg", required=True, help="Type: address"
    )
    is_signer_valid_for_source_parser.add_argument(
        "--source-id", required=True, help="Type: uint256", type=int
    )
    is_signer_valid_for_source_parser.set_defaults(
        func=handle_is_signer_valid_for_source
    )

    name_parser = subcommands.add_parser("name")
    add_default_arguments(name_parser, False)
    name_parser.set_defaults(func=handle_name)

    owner_parser = subcommands.add_parser("owner")
    add_default_arguments(owner_parser, False)
    owner_parser.set_defaults(func=handle_owner)

    owner_of_parser = subcommands.add_parser("owner-of")
    add_default_arguments(owner_of_parser, False)
    owner_of_parser.add_argument(
        "--token-id", required=True, help="Type: uint256", type=int
    )
    owner_of_parser.set_defaults(func=handle_owner_of)

    renounce_ownership_parser = subcommands.add_parser("renounce-ownership")
    add_default_arguments(renounce_ownership_parser, True)
    renounce_ownership_parser.set_defaults(func=handle_renounce_ownership)

    safe_transfer_from_0x42842e0e_parser = subcommands.add_parser(
        "safe-transfer-from-0x42842e0e"
    )
    add_default_arguments(safe_transfer_from_0x42842e0e_parser, True)
    safe_transfer_from_0x42842e0e_parser.add_argument(
        "--from-arg", required=True, help="Type: address"
    )
    safe_transfer_from_0x42842e0e_parser.add_argument(
        "--to", required=True, help="Type: address"
    )
    safe_transfer_from_0x42842e0e_parser.add_argument(
        "--token-id", required=True, help="Type: uint256", type=int
    )
    safe_transfer_from_0x42842e0e_parser.set_defaults(
        func=handle_safe_transfer_from_0x42842e0e
    )

    safe_transfer_from_0xb88d4fde_parser = subcommands.add_parser(
        "safe-transfer-from-0xb88d4fde"
    )
    add_default_arguments(safe_transfer_from_0xb88d4fde_parser, True)
    safe_transfer_from_0xb88d4fde_parser.add_argument(
        "--from-arg", required=True, help="Type: address"
    )
    safe_transfer_from_0xb88d4fde_parser.add_argument(
        "--to", required=True, help="Type: address"
    )
    safe_transfer_from_0xb88d4fde_parser.add_argument(
        "--token-id", required=True, help="Type: uint256", type=int
    )
    safe_transfer_from_0xb88d4fde_parser.add_argument(
        "--data", required=True, help="Type: bytes", type=bytes_argument_type
    )
    safe_transfer_from_0xb88d4fde_parser.set_defaults(
        func=handle_safe_transfer_from_0xb88d4fde
    )

    set_approval_for_all_parser = subcommands.add_parser("set-approval-for-all")
    add_default_arguments(set_approval_for_all_parser, True)
    set_approval_for_all_parser.add_argument(
        "--operator", required=True, help="Type: address"
    )
    set_approval_for_all_parser.add_argument(
        "--approved", required=True, help="Type: bool", type=boolean_argument_type
    )
    set_approval_for_all_parser.set_defaults(func=handle_set_approval_for_all)

    supports_interface_parser = subcommands.add_parser("supports-interface")
    add_default_arguments(supports_interface_parser, False)
    supports_interface_parser.add_argument(
        "--interface-id", required=True, help="Type: bytes4", type=bytes_argument_type
    )
    supports_interface_parser.set_defaults(func=handle_supports_interface)

    symbol_parser = subcommands.add_parser("symbol")
    add_default_arguments(symbol_parser, False)
    symbol_parser.set_defaults(func=handle_symbol)

    token_uri_parser = subcommands.add_parser("token-uri")
    add_default_arguments(token_uri_parser, False)
    token_uri_parser.add_argument(
        "--token-id", required=True, help="Type: uint256", type=int
    )
    token_uri_parser.set_defaults(func=handle_token_uri)

    transfer_from_parser = subcommands.add_parser("transfer-from")
    add_default_arguments(transfer_from_parser, True)
    transfer_from_parser.add_argument("--from-arg", required=True, help="Type: address")
    transfer_from_parser.add_argument("--to", required=True, help="Type: address")
    transfer_from_parser.add_argument(
        "--token-id", required=True, help="Type: uint256", type=int
    )
    transfer_from_parser.set_defaults(func=handle_transfer_from)

    transfer_ownership_parser = subcommands.add_parser("transfer-ownership")
    add_default_arguments(transfer_ownership_parser, True)
    transfer_ownership_parser.add_argument(
        "--new-owner", required=True, help="Type: address"
    )
    transfer_ownership_parser.set_defaults(func=handle_transfer_ownership)

    return parser


def main() -> None:
    parser = generate_cli()
    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
