dependencies:
  - "OpenZeppelin/openzeppelin-contracts@4.8.3"

compiler:
  solc:
    version: 0.8.18
    optimizer:
      enabled: true
      runs: 1024
    remappings:
      - "@openzeppelin-contracts=OpenZeppelin/openzeppelin-contracts@4.8.3"
      - "@openzeppelin/contracts=OpenZeppelin/openzeppelin-contracts@4.8.3"
