dependencies:
  - "OpenZeppelin/openzeppelin-contracts@4.4.0"

compiler:
  solc:
    version: 0.8.21
    optimizer:
      enabled: true
      runs: 1024
    remappings:
      - "@openzeppelin-contracts=OpenZeppelin/openzeppelin-contracts@4.4.0"
      - "@openzeppelin/contracts=OpenZeppelin/openzeppelin-contracts@4.4.0"
