name: Prepare relayers release

on:
  push:
    tags:
      - 'relayers/v*'

jobs:
  create_release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: "Relayers Go client - ${{ github.ref }}"
          body: |
            Version ${{ github.ref }} of the Relayers Go client library and command line tool
          draft: true
          prerelease: false
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
  upload_assets:
    runs-on: ubuntu-20.04
    needs: create_release
    strategy:
      fail-fast: true
      matrix:
        os: ["linux", "darwin", "windows"]
        arch: ["386", "amd64", "arm64"]
        exclude:
          - os: "darwin"
            arch: "arm"
          - os: "darwin"
            arch: "386"
          - os: "windows"
            arch: "arm"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.20.0
      - name: Set version in environment variable
        working-directory: ./relayers
        id: relayers-version
        run: |
          echo "RELAYERS_VERSION=$(cat version.txt)" >> $GITHUB_ENV
      - name: Build binary for each valid (GOOS, GOARCH) pair
        working-directory: ./relayers
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          BUILD_DIR="relayers-${RELAYERS_VERSION}-${GOOS}-${GOARCH}"
          mkdir "$BUILD_DIR"
          cp README.md "$BUILD_DIR/README.md"
          go build -o "$BUILD_DIR/relayers" ./...
          zip -r "$BUILD_DIR.zip" "$BUILD_DIR"
      - name: Upload release asset for each valid (GOOS, GOARH) pair
        working-directory: ./relayers
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./relayers-${RELAYERS_VERSION}-${{ matrix.os }}-${{ matrix.arch }}.zip
          asset_name: relayers-${RELAYERS_VERSION}-${{ matrix.os }}-${{ matrix.arch }}.zip
          asset_content_type: application/zip
