name: Prepare relayers release

on:
  push:
    tags:
      - 'relayers/v*'

defaults:
  run:
    working-directory: relayers

jobs:
  create_release:
    runs-on: ubuntu-20.04
    steps:
      - name: Set env variable for version
        run: echo "GITHUB_REF_VERSION=$(echo ${{ github.ref_name }} | cut -c 10-)" >> $GITHUB_ENV
      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: $GITHUB_REF_VERSION
          release_name: "Relayers Go client - $GITHUB_REF_VERSION"
          body: |
            Version $GITHUB_REF_VERSION of the Relayers Go client library and command line tool
          draft: true
          prerelease: false
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
  upload_assets:
    runs-on: ubuntu-20.04
    needs: create_release
    strategy:
      fail-fast: true
      matrix:
        os: ["linux", "darwin", "windows"]
        arch: ["386", "amd64", "arm64"]
        exclude:
          - os: "darwin"
            arch: "386"
          - os: "windows"
            arch: "arm64"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.20.0
      - name: Build binary for each valid (GOOS, GOARCH) pair
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          BUILD_DIR="relayers-${GITHUB_REF_VERSION}-${GOOS}-${GOARCH}"
          EXTENSION=""
          if [ "$GOOS" = "windows" ]; then
            EXTENSION=".exe"
          fi
          mkdir "$BUILD_DIR"
          cp README.md "$BUILD_DIR/README.md"
          go build -o "$BUILD_DIR/relayers${EXTENSION}" ./...
          zip -r "$BUILD_DIR.zip" "$BUILD_DIR"
      - name: Upload release asset for each valid (GOOS, GOARH) pair
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./relayers-$GITHUB_REF_VERSION-${{ matrix.os }}-${{ matrix.arch }}.zip
          asset_name: relayers-$GITHUB_REF_VERSION-${{ matrix.os }}-${{ matrix.arch }}.zip
          asset_content_type: application/zip
